import Head from "next/head";
import Header from "../components/Header";
import Main from "../components/Main";
import Nft from "../components/Nft";
import AuthPage from "../pages/AuthPage";
import styles from "../styles/Home.module.scss";
import { useMoralis } from "react-moralis";

export default function Home() {
  const { isAuthenticated, authenticate, user, logout, isLoggingOut } =
    useMoralis();
  if (!isAuthenticated) {
    return (
      <>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <AuthPage />
          <button
            onClick={() =>
              authenticate({
                signingMessage: "sign to login to dashboard",
              })
            }
          >
            connect your metamask to get started
          </button>
        </div>
      </>
    );
  }

  return (
    <div>
      <div className={styles.container}>
        <Head>
          <title>Readnet Nft Marketplace</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header user={user} logout={logout} isLoggingOut={isLoggingOut} />
        <Main />
        <Nft user={user} />
      </div>
    </div>
  );
}
